version: "3.7"

networks:
  db-network:
  mail-network:
  app-network:
  public-network:

services:
  public-service:
    container_name: public-service
    image: nginx:1.13
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - public-network
    depends_on:
      - subscription-service

  subscription-service:
    container_name: subscription-service
    build:
      context: .
    networks:
      - public-network
      - app-network
      - mail-network
      - db-network
    depends_on:
      - db-service
      - email-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-service:5432/subscriptions_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db-service:
    container_name: db-service
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-network

  email-service:
    container_name: email-service
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "8025:8025" # Exposed just to check the emails via Mailhog's UI
    networks:
      - mail-network